package com.zhaopj.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-09-09T17:40:25.625+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "MyWebServiceService", 
                  wsdlLocation = "http://192.168.31.42:8888/myWs?wsdl",
                  targetNamespace = "http://webservice.zhaopj.com/") 
public class MyWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.zhaopj.com/", "MyWebServiceService");
    public final static QName MyWebServicePort = new QName("http://webservice.zhaopj.com/", "MyWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.31.42:8888/myWs?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MyWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.31.42:8888/myWs?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MyWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MyWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MyWebServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MyWebServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MyWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns MyWebService
     */
    @WebEndpoint(name = "MyWebServicePort")
    public MyWebService getMyWebServicePort() {
        return super.getPort(MyWebServicePort, MyWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyWebService
     */
    @WebEndpoint(name = "MyWebServicePort")
    public MyWebService getMyWebServicePort(WebServiceFeature... features) {
        return super.getPort(MyWebServicePort, MyWebService.class, features);
    }

}
