package com.zhaopj.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-09-09T09:58:42.121+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://webservice.zhaopj.com/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebMethod
    @Action(input = "http://webservice.zhaopj.com/HelloWorld/sayRequest", output = "http://webservice.zhaopj.com/HelloWorld/sayResponse")
    @RequestWrapper(localName = "say", targetNamespace = "http://webservice.zhaopj.com/", className = "com.zhaopj.webservice.Say")
    @ResponseWrapper(localName = "sayResponse", targetNamespace = "http://webservice.zhaopj.com/", className = "com.zhaopj.webservice.SayResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String say(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
